import {test} from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import {indexedDB} from 'fake-indexeddb';
import React from 'react';
const dom=new JSDOM('<!doctype html><html><body></body></html>',{url:'http://localhost'});
Object.assign(globalThis,{window:dom.window,document:dom.window.document,HTMLElement:dom.window.HTMLElement,localStorage:dom.window.localStorage,IS_REACT_ACT_ENVIRONMENT:true});
Object.defineProperty(globalThis,'navigator',{value:dom.window.navigator,configurable:true});
Object.defineProperty(dom.window,'indexedDB',{value:indexedDB});
const {render,fireEvent,waitFor,cleanup}=await import('@testing-library/react');
const {ChantierWorkspace}=await import('../src/features/workspace/chantier_workspace');
const {AuthProvider}=await import('../src/features/auth/presentation/auth_context');
const {ToastProvider}=await import('../src/core/widgets/feedback/app_toast');
const {IdbAdapter:DB}=await import('../src/core/storage/idb_adapter');
const {ProjectScope}=await import('../src/features/workspace/project_scope');
test('user completes wizard and enters an empty, scoped chantier',async()=>{
 await DB.put('users',{id:'owner',name:'Responsable test',phone:'0100000000',role:'ADMINISTRATEUR',profileCategory:'ADMINISTRATEUR',status:'ACTIVE',mustChangePassword:false,isFirstLoginCompleted:true,createdAt:'now',updatedAt:'now'} as any);
 localStorage.setItem('agb_current_user_id','owner');
 const ui=render(React.createElement(ToastProvider,null,React.createElement(AuthProvider,null,React.createElement(ChantierWorkspace,null,React.createElement('p',null,'Modules du chantier')))));
 await waitFor(()=>assert.ok(ui.queryByText('Créer un chantier / reprendre mon brouillon')));
 fireEvent.click(ui.getByText('Créer un chantier / reprendre mon brouillon'));
 const fill=(label:string,value:string)=>fireEvent.change(ui.getByLabelText(label),{target:{value}});
 fill('Nom du chantier *','Résidence test');fill('Ville *','Abidjan');
 fireEvent.click(ui.getByText('Suivant'));
 fill('Client / maître d’ouvrage *','Client test');
 fireEvent.click(ui.getByText('Suivant'));
 fill('Montant du marché (FCFA) *','2000000');fill('Budget prévisionnel (FCFA) *','1500000');
 fireEvent.click(ui.getByText('Suivant'));
 fill('Début prévu *','2026-09-22');fill('Livraison prévue *','2027-01-01');
 fireEvent.click(ui.getByText('Suivant'));
 fireEvent.click(ui.getByText('Valider et ouvrir le chantier'));
 await waitFor(()=>assert.ok(ui.queryByText('Résidence test')));
 await waitFor(()=>assert.ok(ProjectScope.id));
 assert.equal((await DB.getAllUnscoped<any>('projects'))[0].totalExpensesRealized,0);
 assert.equal(localStorage.getItem('agb_dossier_owner'),null);
 cleanup();
});
