/**
 * AGB CHANTIER - Registre Central des Fonctionnalités & Profils Métiers (Presets)
 * Permet aux clients utilisateurs d'activer ou de désactiver chaque module ou widget à leur convenance.
 */

import { FeatureDefinition, FeaturePreset } from "./feature_toggle_types";

export const CATEGORY_LABELS: Record<string, { label: string; description: string; icon: string }> = {
  operations: {
    label: "Pilotage & Opérations Terrain",
    description: "Supervision des chantiers, plannings Gantt, journal et reportages photo",
    icon: "HardHat",
  },
  human_resources: {
    label: "Ressources Humaines & Sous-Traitance",
    description: "Coordination des intervenants, régie et suivi du pointage ouvriers",
    icon: "Users",
  },
  logistics: {
    label: "Matériaux, Stocks & Matériels",
    description: "Approvisionnements, gestion des engins VGP et commandes fournisseurs",
    icon: "Package",
  },
  finance: {
    label: "Finances, Clients & Décisionnel",
    description: "Suivi budgétaire, clients MOA, situations de travaux et graphiques D3.js",
    icon: "Coins",
  },
  quality_safety: {
    label: "Qualité, HSE & Réception de Chantier",
    description: "Contrôles techniques, registres sécurité SST, PV OPR et levée des réserves",
    icon: "ShieldCheck",
  },
  tools: {
    label: "Outils Avancés & Conformité",
    description: "GED documentaire, scanner QR codes, alertes en temps réel et journal d'audit",
    icon: "Wrench",
  },
  dashboard_widgets: {
    label: "Composants du Tableau de Bord",
    description: "Cartes d'indicateurs, widgets analytiques et outils de synthèse du dashboard",
    icon: "LayoutDashboard",
  },
};

export const ALL_FEATURES: FeatureDefinition[] = [
  // ==========================================
  // 1. OPÉRATIONS TERRAIN
  // ==========================================
  {
    id: "module_projects",
    name: "04. Supervision des Chantiers",
    description: "Portefeuille des chantiers, état d'avancement physique, fiches complètes et géolocalisation.",
    category: "operations",
    categoryLabel: "Pilotage & Opérations Terrain",
    iconName: "HardHat",
    route: "/projects",
    axeNumber: 4,
    isCore: true,
    defaultEnabled: true,
    badge: "Indispensable",
  },
  {
    id: "module_planning",
    name: "06. Planning & Diagramme Gantt",
    description: "Calendrier des phases, jalons charnières, chemin critique et analyse des dérives de planning.",
    category: "operations",
    categoryLabel: "Pilotage & Opérations Terrain",
    iconName: "Calendar",
    route: "/planning",
    axeNumber: 6,
    defaultEnabled: true,
  },
  {
    id: "module_tasks",
    name: "07. Travaux & Tâches par Corps d'État",
    description: "Ordonnancement des tâches d'exécution, assignation aux équipes et suivi des cadences.",
    category: "operations",
    categoryLabel: "Pilotage & Opérations Terrain",
    iconName: "CheckSquare",
    route: "/tasks",
    axeNumber: 7,
    defaultEnabled: true,
  },
  {
    id: "module_site_diary",
    name: "13. Journal de Chantier Quotidien",
    description: "Rapports journaliers des conducteurs : météo, effectifs présents, faits marquants et livraisons.",
    category: "operations",
    categoryLabel: "Pilotage & Opérations Terrain",
    iconName: "BookOpen",
    route: "/site-diary",
    axeNumber: 13,
    defaultEnabled: true,
  },
  {
    id: "module_photos",
    name: "14. Galerie Photos & Géolocalisation",
    description: "Banque visuelle horodatée et géolocalisée pour documenter l'historique et les preuves de travaux.",
    category: "operations",
    categoryLabel: "Pilotage & Opérations Terrain",
    iconName: "Camera",
    route: "/photos",
    axeNumber: 14,
    defaultEnabled: true,
  },

  // ==========================================
  // 2. RESSOURCES HUMAINES & INTERVENANTS
  // ==========================================
  {
    id: "module_teams",
    name: "05. Intervenants & Sous-Traitants",
    description: "Répertoire des entreprises sous-traitantes, équipes régie, contrats et habilitations.",
    category: "human_resources",
    categoryLabel: "Ressources Humaines & Sous-Traitance",
    iconName: "Users",
    route: "/intervenants",
    axeNumber: 5,
    defaultEnabled: true,
  },
  {
    id: "module_attendance",
    name: "08. Pointage & Suivi des Présences",
    description: "Feuilles de pointage quotidiennes, badges ouvriers, heures travaillées et alertes heures sup.",
    category: "human_resources",
    categoryLabel: "Ressources Humaines & Sous-Traitance",
    iconName: "Clock",
    route: "/attendance",
    axeNumber: 8,
    defaultEnabled: true,
  },
  {
    id: "module_admin_users",
    name: "02. Utilisateurs & Permissions RBAC",
    description: "Gestion des accès pour Administrateurs, Gérants, Conducteurs et Collaborateurs.",
    category: "human_resources",
    categoryLabel: "Ressources Humaines & Sous-Traitance",
    iconName: "UserCheck",
    route: "/admin/users",
    axeNumber: 2,
    defaultEnabled: true,
  },

  // ==========================================
  // 3. LOGISTIQUE & MATÉRIAUX
  // ==========================================
  {
    id: "module_inventory",
    name: "09. Matériaux & Gestion des Stocks",
    description: "Suivi des volumes d'aciers, sacs de ciment, sables et seuils d'alerte de réapprovisionnement.",
    category: "logistics",
    categoryLabel: "Matériaux, Stocks & Matériels",
    iconName: "Package",
    route: "/inventory",
    axeNumber: 9,
    defaultEnabled: true,
  },
  {
    id: "module_suppliers",
    name: "10. Fournisseurs & Bons de Commande",
    description: "Catalogues fournisseurs BTP, bons de commande, bons de livraison et factures associées.",
    category: "logistics",
    categoryLabel: "Matériaux, Stocks & Matériels",
    iconName: "Truck",
    route: "/suppliers",
    axeNumber: 10,
    defaultEnabled: true,
  },
  {
    id: "module_equipment",
    name: "12. Parc Engins & Matériels BTP",
    description: "Suivi des grues, engins de terrassement, outillage lourd et échéances de contrôles périodiques VGP.",
    category: "logistics",
    categoryLabel: "Matériaux, Stocks & Matériels",
    iconName: "Wrench",
    route: "/equipment",
    axeNumber: 12,
    defaultEnabled: true,
  },
  {
    id: "module_qr_code",
    name: "22. Scanner QR Code Chantier",
    description: "Contrôle rapide des badges ouvriers et accès direct aux fiches techniques matériels par QR.",
    category: "logistics",
    categoryLabel: "Matériaux, Stocks & Matériels",
    iconName: "QrCode",
    route: "/qr-scanner",
    axeNumber: 22,
    defaultEnabled: true,
  },

  // ==========================================
  // 4. FINANCES & DÉCISIONNEL
  // ==========================================
  {
    id: "module_finance",
    name: "11. Budget, Dépenses & Déboursés",
    description: "Pilotage des budgets d'objectifs, dépenses réelles, marges nettes et retenues de garantie.",
    category: "finance",
    categoryLabel: "Finances, Clients & Décisionnel",
    iconName: "Coins",
    route: "/finance",
    axeNumber: 11,
    defaultEnabled: true,
  },
  {
    id: "module_clients",
    name: "03. Clients & Maîtres d'Ouvrage (MOA)",
    description: "Gestion des maîtres d'ouvrage, promoteurs, ordres de service (OS) et situations de travaux.",
    category: "finance",
    categoryLabel: "Finances, Clients & Décisionnel",
    iconName: "Briefcase",
    route: "/clients",
    axeNumber: 3,
    defaultEnabled: true,
  },
  {
    id: "module_analytics_d3",
    name: "21. Graphiques D3.js & Business Intelligence",
    description: "Visualisations graphiques interactives : courbes en S, consommation budgétaire et ratios d'avancement.",
    category: "finance",
    categoryLabel: "Finances, Clients & Décisionnel",
    iconName: "BarChart3",
    route: "/analytics",
    axeNumber: 21,
    defaultEnabled: true,
  },
  {
    id: "module_reports",
    name: "19. Édition de Rapports & PV BTP",
    description: "Génération automatique de rapports de chantier au format PDF et fiches récapitulatives.",
    category: "finance",
    categoryLabel: "Finances, Clients & Décisionnel",
    iconName: "Printer",
    route: "/reports",
    axeNumber: 19,
    defaultEnabled: true,
  },

  // ==========================================
  // 5. QUALITÉ, SÉCURITÉ & RÉCEPTION
  // ==========================================
  {
    id: "module_quality",
    name: "15. Contrôle Qualité & Conformité",
    description: "Fiches de non-conformité, bons à couler, procès-verbaux d'essais béton et autocontrôles.",
    category: "quality_safety",
    categoryLabel: "Qualité, HSE & Réception de Chantier",
    iconName: "FileCheck",
    route: "/quality",
    axeNumber: 15,
    defaultEnabled: true,
  },
  {
    id: "module_hse",
    name: "16. HSE, Sécurité & Prévention SST",
    description: "Registres de sécurité chantier, déclaration d'accidents, vérifications des EPI et quarts d'heure sécurité.",
    category: "quality_safety",
    categoryLabel: "Qualité, HSE & Réception de Chantier",
    iconName: "AlertTriangle",
    route: "/hse",
    axeNumber: 16,
    defaultEnabled: true,
  },
  {
    id: "module_reservations",
    name: "17. Gestion des Réserves & OPR",
    description: "Recensement des réserves aux Opérations Préalables à la Réception et quitus de levée signé.",
    category: "quality_safety",
    categoryLabel: "Qualité, HSE & Réception de Chantier",
    iconName: "FileCheck",
    route: "/reservations",
    axeNumber: 17,
    defaultEnabled: true,
  },
  {
    id: "module_reception",
    name: "20. Réception de Chantier & DGD",
    description: "Procès-verbaux de réception provisoire, décompte général et définitif (DGD) et parfait achèvement.",
    category: "quality_safety",
    categoryLabel: "Qualité, HSE & Réception de Chantier",
    iconName: "Award",
    route: "/reception",
    axeNumber: 20,
    defaultEnabled: true,
  },

  // ==========================================
  // 6. OUTILS AVANCÉS & CONFORMITÉ
  // ==========================================
  {
    id: "module_documents",
    name: "18. GED Technique & Plans BPE",
    description: "Classement des plans d'architecte, visas des bureaux de contrôle (BC), CCTP et avenants.",
    category: "tools",
    categoryLabel: "Outils Avancés & Conformité",
    iconName: "FileText",
    route: "/documents",
    axeNumber: 18,
    defaultEnabled: true,
  },
  {
    id: "module_notifications",
    name: "23. Centre d'Alertes en Temps Réel",
    description: "Notifications urgentes pour les incidents sécurité, non-conformités et blocages majeurs.",
    category: "tools",
    categoryLabel: "Outils Avancés & Conformité",
    iconName: "Bell",
    route: "/notifications",
    axeNumber: 23,
    defaultEnabled: true,
  },
  {
    id: "module_ai_assistant",
    name: "25. Assistant IA Spécialisé BTP",
    description: "Assistance intelligente pour la détection des risques plannings et l'optimisation des déboursés.",
    category: "tools",
    categoryLabel: "Outils Avancés & Conformité",
    iconName: "Sparkles",
    route: "/ai-assistant",
    axeNumber: 25,
    defaultEnabled: true,
  },
  {
    id: "module_audit",
    name: "26. Registre d'Audit & Traçabilité",
    description: "Historique infalsifiable de toutes les actions, modifications et approbations financières.",
    category: "tools",
    categoryLabel: "Outils Avancés & Conformité",
    iconName: "History",
    route: "/audit",
    axeNumber: 26,
    defaultEnabled: true,
  },

  // ==========================================
  // 7. WIDGETS DU TABLEAU DE BORD (DASHBOARD)
  // ==========================================
  {
    id: "widget_kpi_actifs",
    name: "Widget : Chantiers Actifs & Avancement",
    description: "Carte d'indicateurs synthétisant le volume de projets en cours et le taux d'avancement moyen.",
    category: "dashboard_widgets",
    categoryLabel: "Composants du Tableau de Bord",
    iconName: "HardHat",
    defaultEnabled: true,
  },
  {
    id: "widget_kpi_retards",
    name: "Widget : Alertes Retards & Jalons",
    description: "Carte critique signalant le nombre de chantiers en retard et les dépassements de jalons charnières.",
    category: "dashboard_widgets",
    categoryLabel: "Composants du Tableau de Bord",
    iconName: "AlertTriangle",
    defaultEnabled: true,
  },
  {
    id: "widget_kpi_budget",
    name: "Widget : Budget Total & Engagements",
    description: "Carte financière affichant le montant consolidé des marchés, dépenses et solde budgétaire.",
    category: "dashboard_widgets",
    categoryLabel: "Composants du Tableau de Bord",
    iconName: "Coins",
    defaultEnabled: true,
  },
  {
    id: "widget_milestone_banner",
    name: "Widget : Bannière des Jalons en Dépassement",
    description: "Bannière d'alerte contextuelle rouge et tiroir latéral d'audit des jalons hors délais.",
    category: "dashboard_widgets",
    categoryLabel: "Composants du Tableau de Bord",
    iconName: "Bell",
    defaultEnabled: true,
  },
  {
    id: "widget_csv_export",
    name: "Widget : Bouton d'Exportation CSV BTP",
    description: "Permet de télécharger l'état complet du portefeuille au format CSV compatible Excel.",
    category: "dashboard_widgets",
    categoryLabel: "Composants du Tableau de Bord",
    iconName: "FileSpreadsheet",
    defaultEnabled: true,
  },
  {
    id: "widget_quick_search",
    name: "Widget : Barre de Recherche Rapide & Filtres",
    description: "Champ de recherche textuelle instantanée et boutons de filtres par statut de chantier.",
    category: "dashboard_widgets",
    categoryLabel: "Composants du Tableau de Bord",
    iconName: "Search",
    defaultEnabled: true,
  },
  {
    id: "widget_offline_cache",
    name: "Widget : Bouton Cache Terrain (Service Worker)",
    description: "Accès à la consultation et synchronisation des données chantiers pour le mode hors-ligne.",
    category: "dashboard_widgets",
    categoryLabel: "Composants du Tableau de Bord",
    iconName: "HardDrive",
    defaultEnabled: true,
  },
];

export const FEATURE_PRESETS: FeaturePreset[] = [
  {
    id: "preset_all",
    name: "Suite Complète Tous Corps d'État",
    subtitle: "Tous les 30 axes métiers activés",
    description: "Configuration exhaustive idéale pour les entreprises générales de bâtiment, grands projets et directeurs de travaux.",
    iconName: "Sparkles",
    color: "orange",
    enabledFeatureIds: ALL_FEATURES.map((f) => f.id),
  },
  {
    id: "preset_field",
    name: "Conduite de Travaux & Terrain",
    subtitle: "Chantiers, Planning, Pointage, Journal & Sécurité",
    description: "Concentré sur le terrain : supprime la gestion financière complexe et les modules administratifs pour aller droit au but sur le chantier.",
    iconName: "HardHat",
    color: "amber",
    enabledFeatureIds: [
      "module_projects",
      "module_planning",
      "module_tasks",
      "module_site_diary",
      "module_photos",
      "module_teams",
      "module_attendance",
      "module_equipment",
      "module_qr_code",
      "module_hse",
      "module_quality",
      "module_reservations",
      "module_documents",
      "widget_kpi_actifs",
      "widget_kpi_retards",
      "widget_milestone_banner",
      "widget_quick_search",
      "widget_offline_cache",
    ],
  },
  {
    id: "preset_finance",
    name: "Direction Financière & Commerciale",
    subtitle: "Budgets, Facturation, Clients & BI",
    description: "Conçu pour les DAF, métreurs et gérants : focalisé sur les déboursés, engagements budgétaires, situations clients et graphiques D3.js.",
    iconName: "Coins",
    color: "emerald",
    enabledFeatureIds: [
      "module_projects",
      "module_clients",
      "module_finance",
      "module_suppliers",
      "module_analytics_d3",
      "module_reports",
      "module_documents",
      "module_reception",
      "module_admin_users",
      "module_audit",
      "widget_kpi_actifs",
      "widget_kpi_retards",
      "widget_kpi_budget",
      "widget_csv_export",
      "widget_quick_search",
    ],
  },
  {
    id: "preset_quality_hse",
    name: "Qualité, Sécurité (HSE) & Réception",
    subtitle: "Contrôles, Levée des Réserves, SST & OPR",
    description: "Adapté aux responsables QSE, coordonnateurs SPS et maîtres d'œuvre d'exécution (MOEx) pour garantir la conformité et la sécurité.",
    iconName: "ShieldCheck",
    color: "indigo",
    enabledFeatureIds: [
      "module_projects",
      "module_photos",
      "module_quality",
      "module_hse",
      "module_reservations",
      "module_reception",
      "module_documents",
      "module_reports",
      "module_notifications",
      "widget_kpi_actifs",
      "widget_kpi_retards",
      "widget_milestone_banner",
      "widget_quick_search",
    ],
  },
  {
    id: "preset_artisan_pme",
    name: "Artisan & PME BTP (Pack Essentiel)",
    subtitle: "Chantiers, Planning, Journal & Documents",
    description: "Une interface allégée et intuitive sans encombrement pour les petites équipes et entreprises artisanales du bâtiment.",
    iconName: "Briefcase",
    color: "blue",
    enabledFeatureIds: [
      "module_projects",
      "module_planning",
      "module_site_diary",
      "module_photos",
      "module_finance",
      "module_documents",
      "module_reports",
      "widget_kpi_actifs",
      "widget_kpi_retards",
      "widget_kpi_budget",
      "widget_csv_export",
      "widget_quick_search",
    ],
  },
  {
    id: "preset_custom",
    name: "Configuration Sur-Mesure",
    subtitle: "Sélection personnalisée par l'utilisateur",
    description: "Votre sélection libre d'options et modules ajustée selon vos besoins spécifiques.",
    iconName: "SlidersHorizontal",
    color: "slate",
    enabledFeatureIds: [],
  },
];
